#!/bin/bash
# Runs a Python script

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
       echo "Error: PYFILE envrionment variable is not set."
       exit 1
fi

# Check if the Specified python file eixists
if [ ! -f "$PYFILE" ]; then
	echo "Error: Python file '$PYFILE' not found"
	exit 1
fi

# Run the python script

python3 "$PYFILE"
